-- MySQL Script generated by MySQL Workbench
-- Fri Jul  4 18:58:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trabalho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trabalho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalho` DEFAULT CHARACTER SET utf8 ;
USE `trabalho` ;

-- -----------------------------------------------------
-- Table `trabalho`.`Estado_civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Estado_civil` (
  `idEstado_civil` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado_civil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Sexo` (
  `idSexo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Profissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Profissao` (
  `idProfissao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfissao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Cidade` (
  `idCidade` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Bairro` (
  `idBairro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `Cidade_idCidade` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idBairro`, `Cidade_idCidade`),
  INDEX `fk_Bairro_Cidade1_idx` (`Cidade_idCidade` ASC) VISIBLE,
  CONSTRAINT `fk_Bairro_Cidade1`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `trabalho`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Endereco` (
  `idEndereco` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(9) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `numero` INT NOT NULL,
  `Bairro_idBairro` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEndereco`, `Bairro_idBairro`),
  INDEX `fk_Endereco_Bairro_idx` (`Bairro_idBairro` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Bairro`
    FOREIGN KEY (`Bairro_idBairro`)
    REFERENCES `trabalho`.`Bairro` (`idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Cliente_proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Cliente_proprietario` (
  `idCliente_proprietario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `Estado_civil_idEstado_civil` INT UNSIGNED NOT NULL,
  `Sexo_idSexo` INT UNSIGNED NOT NULL,
  `Proficao_idProficao` INT UNSIGNED NOT NULL,
  `Endereco_idEndereco` INT UNSIGNED NOT NULL,
  `Endereco_Bairro_idBairro` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCliente_proprietario`, `Estado_civil_idEstado_civil`, `Sexo_idSexo`, `Proficao_idProficao`, `Endereco_idEndereco`, `Endereco_Bairro_idBairro`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_Proprietario_Estado_civil1_idx` (`Estado_civil_idEstado_civil` ASC) VISIBLE,
  INDEX `fk_Cliente_proprietario_Sexo1_idx` (`Sexo_idSexo` ASC) VISIBLE,
  INDEX `fk_Cliente_proprietario_Proficao1_idx` (`Proficao_idProficao` ASC) VISIBLE,
  INDEX `fk_Cliente_proprietario_Endereco1_idx` (`Endereco_idEndereco` ASC, `Endereco_Bairro_idBairro` ASC) VISIBLE,
  CONSTRAINT `fk_Proprietario_Estado_civil1`
    FOREIGN KEY (`Estado_civil_idEstado_civil`)
    REFERENCES `trabalho`.`Estado_civil` (`idEstado_civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_proprietario_Sexo1`
    FOREIGN KEY (`Sexo_idSexo`)
    REFERENCES `trabalho`.`Sexo` (`idSexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_proprietario_Proficao1`
    FOREIGN KEY (`Proficao_idProficao`)
    REFERENCES `trabalho`.`Profissao` (`idProfissao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_proprietario_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco` , `Endereco_Bairro_idBairro`)
    REFERENCES `trabalho`.`Endereco` (`idEndereco` , `Bairro_idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Status` (
  `descricao` VARCHAR(45) NOT NULL,
  `idStatus` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Categoria` (
  `idCategoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Visita` (
  `idVisita` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(105) NOT NULL,
  PRIMARY KEY (`idVisita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Imovel` (
  `idImovel` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `foto_url` VARCHAR(45) NOT NULL,
  `valor_sugerido_venda` FLOAT NOT NULL,
  `valor_sugerido_locacao` FLOAT NOT NULL,
  `Cliente_proprietario_idCliente_proprietario` INT UNSIGNED NOT NULL,
  `Cliente_proprietario_Estado_civil_idEstado_civil` INT UNSIGNED NOT NULL,
  `Cliente_proprietario_Sexo_idSexo` INT UNSIGNED NOT NULL,
  `Cliente_proprietario_Proficao_idProficao` INT UNSIGNED NOT NULL,
  `Status_idStatus` INT UNSIGNED NOT NULL,
  `Cliente_usuario_idCliente_usuario` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Estado_civil_idEstado_civil` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Sexo_idSexo` INT UNSIGNED NOT NULL,
  `Categoria_idCategoria` INT UNSIGNED NOT NULL,
  `data_construcao` DATETIME NOT NULL,
  `Visita_idVisita` INT UNSIGNED NOT NULL,
  `Endereco_idEndereco` INT UNSIGNED NOT NULL,
  `Endereco_Bairro_idBairro` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idImovel`, `Cliente_proprietario_idCliente_proprietario`, `Cliente_proprietario_Estado_civil_idEstado_civil`, `Cliente_proprietario_Sexo_idSexo`, `Cliente_proprietario_Proficao_idProficao`, `Status_idStatus`, `Cliente_usuario_idCliente_usuario`, `Cliente_usuario_Estado_civil_idEstado_civil`, `Cliente_usuario_Sexo_idSexo`, `Categoria_idCategoria`, `Visita_idVisita`, `Endereco_idEndereco`, `Endereco_Bairro_idBairro`),
  INDEX `fk_Imovel_Cliente_proprietario1_idx` (`Cliente_proprietario_idCliente_proprietario` ASC, `Cliente_proprietario_Estado_civil_idEstado_civil` ASC, `Cliente_proprietario_Sexo_idSexo` ASC, `Cliente_proprietario_Proficao_idProficao` ASC) VISIBLE,
  INDEX `fk_Imovel_Status1_idx` (`Status_idStatus` ASC) VISIBLE,
  INDEX `fk_Imovel_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  INDEX `fk_Imovel_Visita1_idx` (`Visita_idVisita` ASC) VISIBLE,
  INDEX `fk_Imovel_Endereco1_idx` (`Endereco_idEndereco` ASC, `Endereco_Bairro_idBairro` ASC) VISIBLE,
  CONSTRAINT `fk_Imovel_Cliente_proprietario1`
    FOREIGN KEY (`Cliente_proprietario_idCliente_proprietario` , `Cliente_proprietario_Estado_civil_idEstado_civil` , `Cliente_proprietario_Sexo_idSexo` , `Cliente_proprietario_Proficao_idProficao`)
    REFERENCES `trabalho`.`Cliente_proprietario` (`idCliente_proprietario` , `Estado_civil_idEstado_civil` , `Sexo_idSexo` , `Proficao_idProficao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Imovel_Status1`
    FOREIGN KEY (`Status_idStatus`)
    REFERENCES `trabalho`.`Status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Imovel_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `trabalho`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Imovel_Visita1`
    FOREIGN KEY (`Visita_idVisita`)
    REFERENCES `trabalho`.`Visita` (`idVisita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Imovel_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco` , `Endereco_Bairro_idBairro`)
    REFERENCES `trabalho`.`Endereco` (`idEndereco` , `Bairro_idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Casa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Casa` (
  `idCasa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `qtd_quartos` INT NOT NULL,
  `qtd_suites` INT NOT NULL,
  `qtd_salas_estar` INT NOT NULL,
  `qtd_salas_jantar` INT NOT NULL,
  `vagas_garagem` INT NOT NULL,
  `area_m2` FLOAT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `Imovel_idImovel` INT UNSIGNED NOT NULL,
  `armario_embutido` TINYINT NOT NULL,
  PRIMARY KEY (`idCasa`, `Imovel_idImovel`),
  INDEX `fk_Casa_Imovel1_idx` (`Imovel_idImovel` ASC) VISIBLE,
  CONSTRAINT `fk_Casa_Imovel1`
    FOREIGN KEY (`Imovel_idImovel`)
    REFERENCES `trabalho`.`Imovel` (`idImovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Apartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Apartamento` (
  `idApartamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `qtd_suite` INT NOT NULL,
  `qtd_sala_estar` INT NOT NULL,
  `qtd_sala_jantar` INT NOT NULL,
  `area_m2` FLOAT NOT NULL,
  `armario_embutido` TINYINT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `andar` INT NOT NULL,
  `valor_codominio` FLOAT NOT NULL,
  `vagas_garagem` INT NOT NULL,
  `Imovel_idImovel` INT UNSIGNED NOT NULL,
  `portaria24hrs` TINYINT NOT NULL,
  PRIMARY KEY (`idApartamento`, `Imovel_idImovel`),
  INDEX `fk_Apartamento_Imovel1_idx` (`Imovel_idImovel` ASC) VISIBLE,
  CONSTRAINT `fk_Apartamento_Imovel1`
    FOREIGN KEY (`Imovel_idImovel`)
    REFERENCES `trabalho`.`Imovel` (`idImovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`SalaComercial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`SalaComercial` (
  `idSalaComercial` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `area_m2` FLOAT NOT NULL,
  `qtd_comodos` INT NOT NULL,
  `qtd_banheiros` INT NOT NULL,
  `Imovel_idImovel` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idSalaComercial`, `Imovel_idImovel`),
  INDEX `fk_SalaComercial_Imovel1_idx` (`Imovel_idImovel` ASC) VISIBLE,
  CONSTRAINT `fk_SalaComercial_Imovel1`
    FOREIGN KEY (`Imovel_idImovel`)
    REFERENCES `trabalho`.`Imovel` (`idImovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Tipo_terreno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Tipo_terreno` (
  `idTipo_terreno` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_terreno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Terreno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Terreno` (
  `idTerreno` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `area_m2` FLOAT NOT NULL,
  `largura` FLOAT NOT NULL,
  `comprimento` FLOAT NOT NULL,
  `Imovel_idImovel` INT UNSIGNED NOT NULL,
  `Tipo_terreno_idTipo_terreno` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idTerreno`, `Imovel_idImovel`, `Tipo_terreno_idTipo_terreno`),
  INDEX `fk_Terreno_Imovel1_idx` (`Imovel_idImovel` ASC) VISIBLE,
  INDEX `fk_Terreno_Tipo_terreno1_idx` (`Tipo_terreno_idTipo_terreno` ASC) VISIBLE,
  CONSTRAINT `fk_Terreno_Imovel1`
    FOREIGN KEY (`Imovel_idImovel`)
    REFERENCES `trabalho`.`Imovel` (`idImovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terreno_Tipo_terreno1`
    FOREIGN KEY (`Tipo_terreno_idTipo_terreno`)
    REFERENCES `trabalho`.`Tipo_terreno` (`idTipo_terreno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Fiador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Fiador` (
  `idFiador` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `renda` FLOAT NOT NULL,
  PRIMARY KEY (`idFiador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Indicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Indicacao` (
  `idIndicacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIndicacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`TpoTransação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`TpoTransação` (
  `idTpoTransação` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idTpoTransação`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Transação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Transação` (
  `idTransação` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `valor` VARCHAR(45) NOT NULL,
  `TpoTransação_idTpoTransação` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idTransação`, `TpoTransação_idTpoTransação`),
  INDEX `fk_Transação_TpoTransação1_idx` (`TpoTransação_idTpoTransação` ASC) VISIBLE,
  CONSTRAINT `fk_Transação_TpoTransação1`
    FOREIGN KEY (`TpoTransação_idTpoTransação`)
    REFERENCES `trabalho`.`TpoTransação` (`idTpoTransação`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Comissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Comissao` (
  `idComissao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `porcentagem` FLOAT NOT NULL,
  `Transação_idTransação` INT UNSIGNED NOT NULL,
  `Transação_TpoTransação_idTpoTransação` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idComissao`, `Transação_idTransação`, `Transação_TpoTransação_idTpoTransação`),
  INDEX `fk_Comissao_Transação1_idx` (`Transação_idTransação` ASC, `Transação_TpoTransação_idTpoTransação` ASC) VISIBLE,
  CONSTRAINT `fk_Comissao_Transação1`
    FOREIGN KEY (`Transação_idTransação` , `Transação_TpoTransação_idTpoTransação`)
    REFERENCES `trabalho`.`Transação` (`idTransação` , `TpoTransação_idTpoTransação`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Cliente_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Cliente_usuario` (
  `idCliente_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `Estado_civil_idEstado_civil` INT UNSIGNED NOT NULL,
  `Sexo_idSexo` INT UNSIGNED NOT NULL,
  `Endereco_idEndereco` INT UNSIGNED NOT NULL,
  `Endereco_Bairro_idBairro` INT UNSIGNED NOT NULL,
  `Visita_idVisita` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCliente_usuario`, `Estado_civil_idEstado_civil`, `Sexo_idSexo`, `Endereco_idEndereco`, `Endereco_Bairro_idBairro`, `Visita_idVisita`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_Usuario_Estado_civil1_idx` (`Estado_civil_idEstado_civil` ASC) VISIBLE,
  INDEX `fk_Cliente_usuario_Sexo1_idx` (`Sexo_idSexo` ASC) VISIBLE,
  INDEX `fk_Cliente_usuario_Endereco1_idx` (`Endereco_idEndereco` ASC, `Endereco_Bairro_idBairro` ASC) VISIBLE,
  INDEX `fk_Cliente_usuario_Visita1_idx` (`Visita_idVisita` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Estado_civil1`
    FOREIGN KEY (`Estado_civil_idEstado_civil`)
    REFERENCES `trabalho`.`Estado_civil` (`idEstado_civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_usuario_Sexo1`
    FOREIGN KEY (`Sexo_idSexo`)
    REFERENCES `trabalho`.`Sexo` (`idSexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_usuario_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco` , `Endereco_Bairro_idBairro`)
    REFERENCES `trabalho`.`Endereco` (`idEndereco` , `Bairro_idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_usuario_Visita1`
    FOREIGN KEY (`Visita_idVisita`)
    REFERENCES `trabalho`.`Visita` (`idVisita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Telefone` (
  `idTelefone` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ddd` INT NOT NULL,
  `numero` INT NOT NULL,
  `Cliente_proprietario_idCliente_proprietario` INT UNSIGNED NOT NULL,
  `Cliente_proprietario_Estado_civil_idEstado_civil` INT UNSIGNED NOT NULL,
  `Cliente_proprietario_Sexo_idSexo` INT UNSIGNED NOT NULL,
  `Cliente_proprietario_Proficao_idProficao` INT UNSIGNED NOT NULL,
  `Cliente_proprietario_Endereco_idEndereco` INT UNSIGNED NOT NULL,
  `Cliente_proprietario_Endereco_Bairro_idBairro` INT UNSIGNED NOT NULL,
  `Cliente_usuario_idCliente_usuario` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Estado_civil_idEstado_civil` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Sexo_idSexo` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Endereco_idEndereco` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Endereco_Bairro_idBairro` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Funcionario_idFuncionario` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Funcionario_Sexo_idSexo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idTelefone`, `Cliente_proprietario_idCliente_proprietario`, `Cliente_proprietario_Estado_civil_idEstado_civil`, `Cliente_proprietario_Sexo_idSexo`, `Cliente_proprietario_Proficao_idProficao`, `Cliente_proprietario_Endereco_idEndereco`, `Cliente_proprietario_Endereco_Bairro_idBairro`, `Cliente_usuario_idCliente_usuario`, `Cliente_usuario_Estado_civil_idEstado_civil`, `Cliente_usuario_Sexo_idSexo`, `Cliente_usuario_Endereco_idEndereco`, `Cliente_usuario_Endereco_Bairro_idBairro`, `Cliente_usuario_Funcionario_idFuncionario`, `Cliente_usuario_Funcionario_Sexo_idSexo`),
  INDEX `fk_Telefone_Cliente_proprietario1_idx` (`Cliente_proprietario_idCliente_proprietario` ASC, `Cliente_proprietario_Estado_civil_idEstado_civil` ASC, `Cliente_proprietario_Sexo_idSexo` ASC, `Cliente_proprietario_Proficao_idProficao` ASC, `Cliente_proprietario_Endereco_idEndereco` ASC, `Cliente_proprietario_Endereco_Bairro_idBairro` ASC) VISIBLE,
  INDEX `fk_Telefone_Cliente_usuario1_idx` (`Cliente_usuario_idCliente_usuario` ASC, `Cliente_usuario_Estado_civil_idEstado_civil` ASC, `Cliente_usuario_Sexo_idSexo` ASC, `Cliente_usuario_Endereco_idEndereco` ASC, `Cliente_usuario_Endereco_Bairro_idBairro` ASC, `Cliente_usuario_Funcionario_idFuncionario` ASC, `Cliente_usuario_Funcionario_Sexo_idSexo` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Cliente_proprietario1`
    FOREIGN KEY (`Cliente_proprietario_idCliente_proprietario` , `Cliente_proprietario_Estado_civil_idEstado_civil` , `Cliente_proprietario_Sexo_idSexo` , `Cliente_proprietario_Proficao_idProficao` , `Cliente_proprietario_Endereco_idEndereco` , `Cliente_proprietario_Endereco_Bairro_idBairro`)
    REFERENCES `trabalho`.`Cliente_proprietario` (`idCliente_proprietario` , `Estado_civil_idEstado_civil` , `Sexo_idSexo` , `Proficao_idProficao` , `Endereco_idEndereco` , `Endereco_Bairro_idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefone_Cliente_usuario1`
    FOREIGN KEY (`Cliente_usuario_idCliente_usuario` , `Cliente_usuario_Estado_civil_idEstado_civil` , `Cliente_usuario_Sexo_idSexo` , `Cliente_usuario_Endereco_idEndereco` , `Cliente_usuario_Endereco_Bairro_idBairro`)
    REFERENCES `trabalho`.`Cliente_usuario` (`idCliente_usuario` , `Estado_civil_idEstado_civil` , `Sexo_idSexo` , `Endereco_idEndereco` , `Endereco_Bairro_idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Funcionario` (
  `idFuncionario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `salario_total` VARCHAR(45) NOT NULL,
  `Sexo_idSexo` INT UNSIGNED NOT NULL,
  `Comissao_idComissao` INT UNSIGNED NOT NULL,
  `Comissao_Transação_idTransação` INT UNSIGNED NOT NULL,
  `Comissao_Transação_TpoTransação_idTpoTransação` INT UNSIGNED NOT NULL,
  `Telefone_idTelefone` INT UNSIGNED NOT NULL,
  `Endereco_idEndereco` INT UNSIGNED NOT NULL,
  `Endereco_Bairro_idBairro` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idFuncionario`, `Sexo_idSexo`, `Comissao_idComissao`, `Comissao_Transação_idTransação`, `Comissao_Transação_TpoTransação_idTpoTransação`, `Telefone_idTelefone`, `Endereco_idEndereco`, `Endereco_Bairro_idBairro`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_Funcionario_Sexo1_idx` (`Sexo_idSexo` ASC) VISIBLE,
  INDEX `fk_Funcionario_Comissao1_idx` (`Comissao_idComissao` ASC, `Comissao_Transação_idTransação` ASC, `Comissao_Transação_TpoTransação_idTpoTransação` ASC) VISIBLE,
  INDEX `fk_Funcionario_Telefone1_idx` (`Telefone_idTelefone` ASC) VISIBLE,
  INDEX `fk_Funcionario_Endereco1_idx` (`Endereco_idEndereco` ASC, `Endereco_Bairro_idBairro` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Sexo1`
    FOREIGN KEY (`Sexo_idSexo`)
    REFERENCES `trabalho`.`Sexo` (`idSexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Comissao1`
    FOREIGN KEY (`Comissao_idComissao` , `Comissao_Transação_idTransação` , `Comissao_Transação_TpoTransação_idTpoTransação`)
    REFERENCES `trabalho`.`Comissao` (`idComissao` , `Transação_idTransação` , `Transação_TpoTransação_idTpoTransação`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Telefone1`
    FOREIGN KEY (`Telefone_idTelefone`)
    REFERENCES `trabalho`.`Telefone` (`idTelefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco` , `Endereco_Bairro_idBairro`)
    REFERENCES `trabalho`.`Endereco` (`idEndereco` , `Bairro_idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Cargo` (
  `idCargo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `salario_base` FLOAT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Manutencao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Manutencao` (
  `idManutencao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(105) NOT NULL,
  `Imovel_idImovel` INT UNSIGNED NOT NULL,
  `Imovel_Cliente_proprietario_idCliente_proprietario` INT UNSIGNED NOT NULL,
  `Imovel_Cliente_proprietario_Estado_civil_idEstado_civil` INT UNSIGNED NOT NULL,
  `Imovel_Cliente_proprietario_Sexo_idSexo` INT UNSIGNED NOT NULL,
  `Imovel_Cliente_proprietario_Proficao_idProficao` INT UNSIGNED NOT NULL,
  `Imovel_Status_idStatus` INT UNSIGNED NOT NULL,
  `Imovel_Cliente_usuario_idCliente_usuario` INT UNSIGNED NOT NULL,
  `Imovel_Cliente_usuario_Estado_civil_idEstado_civil` INT UNSIGNED NOT NULL,
  `Imovel_Cliente_usuario_Sexo_idSexo` INT UNSIGNED NOT NULL,
  `Imovel_Categoria_idCategoria` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idManutencao`, `Imovel_idImovel`, `Imovel_Cliente_proprietario_idCliente_proprietario`, `Imovel_Cliente_proprietario_Estado_civil_idEstado_civil`, `Imovel_Cliente_proprietario_Sexo_idSexo`, `Imovel_Cliente_proprietario_Proficao_idProficao`, `Imovel_Status_idStatus`, `Imovel_Cliente_usuario_idCliente_usuario`, `Imovel_Cliente_usuario_Estado_civil_idEstado_civil`, `Imovel_Cliente_usuario_Sexo_idSexo`, `Imovel_Categoria_idCategoria`),
  INDEX `fk_Manutencao_Imovel1_idx` (`Imovel_idImovel` ASC, `Imovel_Cliente_proprietario_idCliente_proprietario` ASC, `Imovel_Cliente_proprietario_Estado_civil_idEstado_civil` ASC, `Imovel_Cliente_proprietario_Sexo_idSexo` ASC, `Imovel_Cliente_proprietario_Proficao_idProficao` ASC, `Imovel_Status_idStatus` ASC, `Imovel_Cliente_usuario_idCliente_usuario` ASC, `Imovel_Cliente_usuario_Estado_civil_idEstado_civil` ASC, `Imovel_Cliente_usuario_Sexo_idSexo` ASC, `Imovel_Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Manutencao_Imovel1`
    FOREIGN KEY (`Imovel_idImovel` , `Imovel_Cliente_proprietario_idCliente_proprietario` , `Imovel_Cliente_proprietario_Estado_civil_idEstado_civil` , `Imovel_Cliente_proprietario_Sexo_idSexo` , `Imovel_Cliente_proprietario_Proficao_idProficao` , `Imovel_Status_idStatus` , `Imovel_Cliente_usuario_idCliente_usuario` , `Imovel_Cliente_usuario_Estado_civil_idEstado_civil` , `Imovel_Cliente_usuario_Sexo_idSexo` , `Imovel_Categoria_idCategoria`)
    REFERENCES `trabalho`.`Imovel` (`idImovel` , `Cliente_proprietario_idCliente_proprietario` , `Cliente_proprietario_Estado_civil_idEstado_civil` , `Cliente_proprietario_Sexo_idSexo` , `Cliente_proprietario_Proficao_idProficao` , `Status_idStatus` , `Cliente_usuario_idCliente_usuario` , `Cliente_usuario_Estado_civil_idEstado_civil` , `Cliente_usuario_Sexo_idSexo` , `Categoria_idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Contrato` (
  `idContrato` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `documento` LONGTEXT NOT NULL,
  `data_contrato` VARCHAR(45) NOT NULL,
  `Cliente_proprietario_idCliente_proprietario` INT UNSIGNED NOT NULL,
  `Cliente_proprietario_Estado_civil_idEstado_civil` INT UNSIGNED NOT NULL,
  `Cliente_proprietario_Sexo_idSexo` INT UNSIGNED NOT NULL,
  `Cliente_proprietario_Proficao_idProficao` INT UNSIGNED NOT NULL,
  `Cliente_proprietario_Endereco_idEndereco` INT UNSIGNED NOT NULL,
  `Cliente_proprietario_Endereco_Bairro_idBairro` INT UNSIGNED NOT NULL,
  `Cliente_usuario_idCliente_usuario` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Estado_civil_idEstado_civil` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Sexo_idSexo` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Endereco_idEndereco` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Endereco_Bairro_idBairro` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Visita_idVisita` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idContrato`, `Cliente_proprietario_idCliente_proprietario`, `Cliente_proprietario_Estado_civil_idEstado_civil`, `Cliente_proprietario_Sexo_idSexo`, `Cliente_proprietario_Proficao_idProficao`, `Cliente_proprietario_Endereco_idEndereco`, `Cliente_proprietario_Endereco_Bairro_idBairro`, `Cliente_usuario_idCliente_usuario`, `Cliente_usuario_Estado_civil_idEstado_civil`, `Cliente_usuario_Sexo_idSexo`, `Cliente_usuario_Endereco_idEndereco`, `Cliente_usuario_Endereco_Bairro_idBairro`, `Cliente_usuario_Visita_idVisita`),
  INDEX `fk_Contrato_Cliente_proprietario1_idx` (`Cliente_proprietario_idCliente_proprietario` ASC, `Cliente_proprietario_Estado_civil_idEstado_civil` ASC, `Cliente_proprietario_Sexo_idSexo` ASC, `Cliente_proprietario_Proficao_idProficao` ASC, `Cliente_proprietario_Endereco_idEndereco` ASC, `Cliente_proprietario_Endereco_Bairro_idBairro` ASC) VISIBLE,
  INDEX `fk_Contrato_Cliente_usuario1_idx` (`Cliente_usuario_idCliente_usuario` ASC, `Cliente_usuario_Estado_civil_idEstado_civil` ASC, `Cliente_usuario_Sexo_idSexo` ASC, `Cliente_usuario_Endereco_idEndereco` ASC, `Cliente_usuario_Endereco_Bairro_idBairro` ASC, `Cliente_usuario_Visita_idVisita` ASC) VISIBLE,
  CONSTRAINT `fk_Contrato_Cliente_proprietario1`
    FOREIGN KEY (`Cliente_proprietario_idCliente_proprietario` , `Cliente_proprietario_Estado_civil_idEstado_civil` , `Cliente_proprietario_Sexo_idSexo` , `Cliente_proprietario_Proficao_idProficao` , `Cliente_proprietario_Endereco_idEndereco` , `Cliente_proprietario_Endereco_Bairro_idBairro`)
    REFERENCES `trabalho`.`Cliente_proprietario` (`idCliente_proprietario` , `Estado_civil_idEstado_civil` , `Sexo_idSexo` , `Proficao_idProficao` , `Endereco_idEndereco` , `Endereco_Bairro_idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_Cliente_usuario1`
    FOREIGN KEY (`Cliente_usuario_idCliente_usuario` , `Cliente_usuario_Estado_civil_idEstado_civil` , `Cliente_usuario_Sexo_idSexo` , `Cliente_usuario_Endereco_idEndereco` , `Cliente_usuario_Endereco_Bairro_idBairro` , `Cliente_usuario_Visita_idVisita`)
    REFERENCES `trabalho`.`Cliente_usuario` (`idCliente_usuario` , `Estado_civil_idEstado_civil` , `Sexo_idSexo` , `Endereco_idEndereco` , `Endereco_Bairro_idBairro` , `Visita_idVisita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Cargo_has_Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Cargo_has_Funcionario` (
  `Cargo_idCargo` INT UNSIGNED NOT NULL,
  `Funcionario_idFuncionario` INT UNSIGNED NOT NULL,
  `Funcionario_Sexo_idSexo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Cargo_idCargo`, `Funcionario_idFuncionario`, `Funcionario_Sexo_idSexo`),
  INDEX `fk_Cargo_has_Funcionario_Funcionario1_idx` (`Funcionario_idFuncionario` ASC, `Funcionario_Sexo_idSexo` ASC) VISIBLE,
  INDEX `fk_Cargo_has_Funcionario_Cargo1_idx` (`Cargo_idCargo` ASC) VISIBLE,
  CONSTRAINT `fk_Cargo_has_Funcionario_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `trabalho`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargo_has_Funcionario_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario` , `Funcionario_Sexo_idSexo`)
    REFERENCES `trabalho`.`Funcionario` (`idFuncionario` , `Sexo_idSexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Locacao` (
  `idLocacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Transação_idTransação` INT UNSIGNED NOT NULL,
  `Transação_TpoTransação_idTpoTransação` INT UNSIGNED NOT NULL,
  `Cliente_usuario_idCliente_usuario` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Estado_civil_idEstado_civil` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Sexo_idSexo` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Endereco_idEndereco` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Endereco_Bairro_idBairro` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Funcionario_idFuncionario` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Funcionario_Sexo_idSexo` INT UNSIGNED NOT NULL,
  `Funcionario_idFuncionario` INT UNSIGNED NOT NULL,
  `Funcionario_Sexo_idSexo` INT UNSIGNED NOT NULL,
  `data_locacao` DATETIME NOT NULL,
  PRIMARY KEY (`idLocacao`, `Transação_idTransação`, `Transação_TpoTransação_idTpoTransação`, `Cliente_usuario_idCliente_usuario`, `Cliente_usuario_Estado_civil_idEstado_civil`, `Cliente_usuario_Sexo_idSexo`, `Cliente_usuario_Endereco_idEndereco`, `Cliente_usuario_Endereco_Bairro_idBairro`, `Cliente_usuario_Funcionario_idFuncionario`, `Cliente_usuario_Funcionario_Sexo_idSexo`, `Funcionario_idFuncionario`, `Funcionario_Sexo_idSexo`),
  INDEX `fk_Locacao_Transação1_idx` (`Transação_idTransação` ASC, `Transação_TpoTransação_idTpoTransação` ASC) VISIBLE,
  INDEX `fk_Locacao_Cliente_usuario1_idx` (`Cliente_usuario_idCliente_usuario` ASC, `Cliente_usuario_Estado_civil_idEstado_civil` ASC, `Cliente_usuario_Sexo_idSexo` ASC, `Cliente_usuario_Endereco_idEndereco` ASC, `Cliente_usuario_Endereco_Bairro_idBairro` ASC, `Cliente_usuario_Funcionario_idFuncionario` ASC, `Cliente_usuario_Funcionario_Sexo_idSexo` ASC) VISIBLE,
  INDEX `fk_Locacao_Funcionario1_idx` (`Funcionario_idFuncionario` ASC, `Funcionario_Sexo_idSexo` ASC) VISIBLE,
  CONSTRAINT `fk_Locacao_Transação1`
    FOREIGN KEY (`Transação_idTransação` , `Transação_TpoTransação_idTpoTransação`)
    REFERENCES `trabalho`.`Transação` (`idTransação` , `TpoTransação_idTpoTransação`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locacao_Cliente_usuario1`
    FOREIGN KEY (`Cliente_usuario_idCliente_usuario` , `Cliente_usuario_Estado_civil_idEstado_civil` , `Cliente_usuario_Sexo_idSexo` , `Cliente_usuario_Endereco_idEndereco` , `Cliente_usuario_Endereco_Bairro_idBairro`)
    REFERENCES `trabalho`.`Cliente_usuario` (`idCliente_usuario` , `Estado_civil_idEstado_civil` , `Sexo_idSexo` , `Endereco_idEndereco` , `Endereco_Bairro_idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locacao_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario` , `Funcionario_Sexo_idSexo`)
    REFERENCES `trabalho`.`Funcionario` (`idFuncionario` , `Sexo_idSexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Indicacao_has_Locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Indicacao_has_Locacao` (
  `Indicacao_idIndicacao` INT UNSIGNED NOT NULL,
  `Locacao_idLocacao` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Indicacao_idIndicacao`, `Locacao_idLocacao`),
  INDEX `fk_Indicacao_has_Locacao_Locacao1_idx` (`Locacao_idLocacao` ASC) VISIBLE,
  INDEX `fk_Indicacao_has_Locacao_Indicacao1_idx` (`Indicacao_idIndicacao` ASC) VISIBLE,
  CONSTRAINT `fk_Indicacao_has_Locacao_Indicacao1`
    FOREIGN KEY (`Indicacao_idIndicacao`)
    REFERENCES `trabalho`.`Indicacao` (`idIndicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Indicacao_has_Locacao_Locacao1`
    FOREIGN KEY (`Locacao_idLocacao`)
    REFERENCES `trabalho`.`Locacao` (`idLocacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Fiador_has_Locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Fiador_has_Locacao` (
  `Fiador_idFiador` INT UNSIGNED NOT NULL,
  `Locacao_idLocacao` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Fiador_idFiador`, `Locacao_idLocacao`),
  INDEX `fk_Fiador_has_Locacao_Locacao1_idx` (`Locacao_idLocacao` ASC) VISIBLE,
  INDEX `fk_Fiador_has_Locacao_Fiador1_idx` (`Fiador_idFiador` ASC) VISIBLE,
  CONSTRAINT `fk_Fiador_has_Locacao_Fiador1`
    FOREIGN KEY (`Fiador_idFiador`)
    REFERENCES `trabalho`.`Fiador` (`idFiador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fiador_has_Locacao_Locacao1`
    FOREIGN KEY (`Locacao_idLocacao`)
    REFERENCES `trabalho`.`Locacao` (`idLocacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`Compra` (
  `idCompra` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_compra` DATETIME NOT NULL,
  `Transação_idTransação` INT UNSIGNED NOT NULL,
  `Transação_TpoTransação_idTpoTransação` INT UNSIGNED NOT NULL,
  `Cliente_usuario_idCliente_usuario` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Estado_civil_idEstado_civil` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Sexo_idSexo` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Endereco_idEndereco` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Endereco_Bairro_idBairro` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Funcionario_idFuncionario` INT UNSIGNED NOT NULL,
  `Cliente_usuario_Funcionario_Sexo_idSexo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCompra`, `Transação_idTransação`, `Transação_TpoTransação_idTpoTransação`, `Cliente_usuario_idCliente_usuario`, `Cliente_usuario_Estado_civil_idEstado_civil`, `Cliente_usuario_Sexo_idSexo`, `Cliente_usuario_Endereco_idEndereco`, `Cliente_usuario_Endereco_Bairro_idBairro`, `Cliente_usuario_Funcionario_idFuncionario`, `Cliente_usuario_Funcionario_Sexo_idSexo`),
  INDEX `fk_Compra_Transação1_idx` (`Transação_idTransação` ASC, `Transação_TpoTransação_idTpoTransação` ASC) VISIBLE,
  INDEX `fk_Compra_Cliente_usuario1_idx` (`Cliente_usuario_idCliente_usuario` ASC, `Cliente_usuario_Estado_civil_idEstado_civil` ASC, `Cliente_usuario_Sexo_idSexo` ASC, `Cliente_usuario_Endereco_idEndereco` ASC, `Cliente_usuario_Endereco_Bairro_idBairro` ASC, `Cliente_usuario_Funcionario_idFuncionario` ASC, `Cliente_usuario_Funcionario_Sexo_idSexo` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Transação1`
    FOREIGN KEY (`Transação_idTransação` , `Transação_TpoTransação_idTpoTransação`)
    REFERENCES `trabalho`.`Transação` (`idTransação` , `TpoTransação_idTpoTransação`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Cliente_usuario1`
    FOREIGN KEY (`Cliente_usuario_idCliente_usuario` , `Cliente_usuario_Estado_civil_idEstado_civil` , `Cliente_usuario_Sexo_idSexo` , `Cliente_usuario_Endereco_idEndereco` , `Cliente_usuario_Endereco_Bairro_idBairro`)
    REFERENCES `trabalho`.`Cliente_usuario` (`idCliente_usuario` , `Estado_civil_idEstado_civil` , `Sexo_idSexo` , `Endereco_idEndereco` , `Endereco_Bairro_idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
